# Eons-Core
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ArmouredHeart/Eons-Core/issues"

[[mods]]
modId="eons-core"
version="${file.jarVersion}"
displayName="Eons-Core"
#updateJSONURL=""
#displayURL="https://github.com/ArmouredHeart/Eons-Core"
logoFile="EonsCore_Logo.png"
credits="sample text"
authors="ArmouredHeart, Accentaur"
description='''This is Eons!'''
# Forge
[[dependencies.eons_core]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.eons_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"