# Eons-Core
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/ArmouredHeart/Eons-Core/issues"

[[mods]]
modId="eons-core"
version="${version}"
displayName="Eons"
#updateJSONURL=""
displayURL="not on curseforge yet lol"
logoFile="EonsCore_Logo.png"
#credits="sample text"
authors="ArmouredHeart, Accentaur"
description='''
Grab your notebook and learn about the history of life on Earth with 300+ prehistoric mobs!
'''
# Forge
[[dependencies.eons_core]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.eons_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"